# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-05 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('auctionitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctionapp.AuctionItem')),
            ],
        ),
    ]
